### ISSUE TITLE
anyting is blank ?

### ISSUE THREAD

**Issue by firstsko** [vue-workflow-chart/vue-workflow-chart#13]
**Describe the bug**
<template>
  <div class="row">
        <div id="app">
          <workflow-chart :transitions="transitions" :states="states"  :stateSemantics="stateSemantics" @state-click="onStateClick($event)" />
    </div>
  </div>
</template>
<style lang="scss">
@import '~vue-workflow-chart/dist/vue-workflow-chart.css';

</style> 
<script>
import WorkflowChart from "vue-workflow-chart";

export default {
  data() {
    return {
      states: [
        {
          id: "state_1",
          label: "State 1"
        },
        {
          id: "state_2",
          label: "State 2"
        }
      ],
      transitions: [
        {
          id: "transition_1",
          label: "this is a transition",
          target: "state_2",
          source: "state_1"
        }
      ]
    };
  },
  computed: {},
  components: {
    WorkflowChart
  },
  methods: {
        onStateClick(id) {
            alert(`Clicked on state with id: ${id}`);
        },
  },
  mounted() {},

  filters: {}
};

**Screenshots**
display nothing on the page?

**Desktop (please complete the following information):**
 - OS: [MACOS]
 - Browser [chrome, safari]

**Additional context**
anyting problem?

**Comment by da-snap** [comment]
It works for me, when I add the template part to the vue file:
```
<template>
    <div id="app">
        <workflow-chart
            :transitions="transitions"
            :states="states" />
    </div>
</template>
```
